receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'rasa'
          static_configs:
            - targets: ['rasa:9091']

        - job_name: 'dcgm-exporter'
          static_configs:
            - targets: ['dcgm-exporter:9400']

        - job_name: 'redisai'
          static_configs:
            - targets: ['redisai-exporter:9121']  # Exporter Prometheus para RedisAI

        - job_name: 'prometheus-self'
          static_configs:
            - targets: ['prometheus:9090']

        - job_name: 'grafana'
          static_configs:
            - targets: ['grafana:3000']  # Requer habilitar métricas no grafana.ini

        # Removido influxdb até ter um exporter funcional
        # - job_name: 'influxdb'
        #   static_configs:
        #     - targets: ['influxdb:8086']

  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 400
    spike_limit_mib: 100

  batch:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"

  debug:
    verbosity: detailed

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [memory_limiter, batch]
      exporters: [prometheus, debug]

    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]  # ou [otlp] se o Tempo estiver ativado

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
