---
receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'rasa'
          static_configs:
            - targets: ['rasa:9091']
          scrape_interval: 15s
          scrape_timeout: 10s

        - job_name: 'dcgm-exporter'
          static_configs:
            - targets: ['dcgm-exporter:9400']
          scrape_interval: 15s
          scrape_timeout: 10s

        - job_name: 'redisai'
          static_configs:
            - targets: ['redisai-exporter:9121']
          scrape_interval: 15s
          scrape_timeout: 10s

        - job_name: 'prometheus-self'
          static_configs:
            - targets: ['prometheus:9090']
          scrape_interval: 30s
          scrape_timeout: 10s

        - job_name: 'grafana'
          static_configs:
            - targets: ['grafana:3000']
          scrape_interval: 30s
          scrape_timeout: 10s

        - job_name: 'glpi'
          metrics_path: /probe
          params:
            module: [http_2xx]
          static_configs:
            - targets: ['http://glpi.local']
          relabel_configs:
            - source_labels: [__address__]
              target_label: __param_target
            - source_labels: [__param_target]
              target_label: instance
            - target_label: __address__
              replacement: blackbox-exporter:9115

        - job_name: 'sia'
          metrics_path: /probe
          params:
            module: [http_2xx]
          static_configs:
            - targets: ['http://sia.local']
          relabel_configs:
            - source_labels: [__address__]
              target_label: __param_target
            - source_labels: [__param_target]
              target_label: instance
            - target_label: __address__
              replacement: blackbox-exporter:9115

        - job_name: 'superset'
          metrics_path: /probe
          params:
            module: [http_2xx]
          static_configs:
            - targets: ['http://superset:8088']
          relabel_configs:
            - source_labels: [__address__]
              target_label: __param_target
            - source_labels: [__param_target]
              target_label: instance
            - target_label: __address__
              replacement: blackbox-exporter:9115

        - job_name: 'metabase'
          metrics_path: /probe
          params:
            module: [http_2xx]
          static_configs:
            - targets: ['http://metabase:3001']
          relabel_configs:
            - source_labels: [__address__]
              target_label: __param_target
            - source_labels: [__param_target]
              target_label: instance
            - target_label: __address__
              replacement: blackbox-exporter:9115

        - job_name: 'redpanda'
          static_configs:
            - targets: ['redpanda:9644']
          scrape_interval: 30s
          scrape_timeout: 10s

        - job_name: 'ollama'
          static_configs:
            - targets: ['ollama:11434']
          scrape_interval: 30s
          scrape_timeout: 10s

        - job_name: 'llama'
          static_configs:
            - targets: ['llama:5000']
          scrape_interval: 30s
          scrape_timeout: 10s

        - job_name: 'milvus'
          static_configs:
            - targets: ['milvus:9092']
          scrape_interval: 30s
          scrape_timeout: 10s

  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 400
    spike_limit_mib: 100

  batch:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"

  debug:
    verbosity: detailed

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [memory_limiter, batch]
      exporters: [prometheus, debug]

    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
